### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by Offender27** [master7720/VodkaWare-1.0.0-beta-leak#1]
XULU SKID WOW U THOUGHT I TRUST U?

**Comment by master7720** [comment]
yes

**Comment by master7720** [comment]
cope

**Comment by Offender27** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOLL

**Comment by master7720** [comment]
you were beging me in dms about skiding xulu

**Comment by master7720** [comment]
https://user-images.githubusercontent.com/59320967/144741331-a423c539-afd1-41e5-abe1-615bb663a377.gif
